### PR TITLE
Crazycarl: Make RPG face where its actually aiming

### PR DESCRIPTION
**Pull request by squeek502**
- This is part of a commit by Crazycarl merged over from the old model SVN
- See fortressforever/fortressforever#146

From the SVN log:

> Attempt to make w_RPG model line up with the rocket trajectory, and new "shoot" animation

---

Not sure if this addresses @AfterShockFF's concerns or not, but it seems to be a worthwhile improvement to the firing animation regardless.
### Before:

2016-06-07 21-41-30-clip-1 2879708383961-1 7987418226593
### After:

2016-06-07 21-39-03-clip-0 28979343863913-1 8298906439854

### CODE REVIEW

**Comment by doublah** [comment]
Might just be me but this looks like it moves the head and the character is constantly leaning to their right, would this affect headshots and such?

**Comment by squeek502** [comment]
Not actually sure how the hitboxes get defined. I would assume it would affect that, but I'm not certain.

**Comment by doublah** [comment]
While it may be different, if the player shoots any part of the head and it still counts as a headshot, then there are no problems in my opinion. Will need testing I guess.

**Comment by squeek502** [comment]
Yeah, headshots have always been pretty broken. I forget the exact circumstances now, but I remember the_cake showed me that you can shoot through peoples heads without damaging them at certain angles or something.

**Comment by WillWowmc** [comment]
Hitboxes are defined in a model's .qc from what I've seen; I think they are parented to a certain bone, and told the boundaries. But on decompiling the soldier playermodel, it's come out with a .qc that has the hitbox definitions commented out... that's probably a thingo in the decompiler doing that, I hope!

**Comment by squeek502** [comment]
Merging. Can still be improved, but it's good enough for now.

**Pull request merged**
